{{- if ((.Values.networking).expose) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: clusterissuer-nginx
  name: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.networking.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.networking.domain }}
      secretName: {{ .Values.networking.domain }}-tls
  {{- end }}
