general:
  image: registry.cloudless.no/public/example-spa
  version: latest
  environment:
    ENVIRONMENT: production

mongodb:
  enabled: false

scaling:
  replicas: 1

networking:
  expose: true
  domain: 
  type: ClusterIP
